export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

export const LOGIN_FORM_CHANGE = 'LOGIN_FORM_CHANGE';
export const LOGIN = 'LOGIN';
export const FETCH_LOGIN = 'FETCH_LOGIN';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const TOKEN_LOGIN = 'TOKEN_LOGIN';
export const TOKEN_LOGIN_SUCCESS = 'TOKEN_LOGIN_SUCCESS';

export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';

export const FETCH_USER_LIST = 'FETCH_USER_LIST';
export const FETCH_USER_LIST_SUCCESS = 'FETCH_USER_LIST_SUCCESS';
export const FETCH_USER_LIST_ERROR = 'FETCH_USER_LIST_ERROR';
export const UPLOAD_AVATOR = 'UPLOAD_AVATOR';
export const USER_STATUS_CHANGE = 'USER_STATUS_CHANGE';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

export const FETCH_CUSTOMER_LIST = 'FETCH_CUSTOMER_LIST';
export const FETCH_CUSTOMER_LIST_SUCCESS = 'FETCH_CUSTOMER_LIST_SUCCESS';
export const FETCH_CUSTOMER_LIST_ERROR = 'FETCH_CUSTOMER_LIST_ERROR';
export const FETCH_CUSTOMER = 'FETCH_CUSTOMER';
export const FETCH_CUSTOMER_SUCCESS = 'FETCH_CUSTOMER_SUCCESS';
export const FETCH_CUSTOMER_ERROR = 'FETCH_CUSTOMER_ERROR';
export const FETCH_WEBMASTER_CUSTOMER = 'FETCH_WEBMASTER_CUSTOMER';
export const FETCH_WEBMASTER_CUSTOMER_SUCCESS = 'FETCH_WEBMASTER_CUSTOMER_SUCCESS';
export const FETCH_WEBMASTER_CUSTOMER_ERROR = 'FETCH_WEBMASTER_CUSTOMER_ERROR';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_ERROR = 'UPDATE_CUSTOMER_ERROR';
export const UPDATE_WAITER = 'UPDATE_WAITER';
export const UPDATE_WAITER_SUCCESS = 'UPDATE_WAITER_SUCCESS';
export const UPDATE_WAITER_ERROR = 'UPDATE_WAITER_ERROR';
