import { createFormReducer } from '../common';

export default createFormReducer({
    editingUser: {},
    addUser: {
        avator: '',
        email: '',
        password: '',
        name: '',
        mobile: '',
        role: 'webmaster',
        note: '',
        is_active: true,
    },
    profile: {},
    customer: {},
    category: {
        name: '',
        description: '',
        parent_category_id: 0,
        image: {},
    },
    supplier: {
        name: '',
        address: '',
        phone: '',
        star: '',
        note: '',
        home_page: '',
        contacts: '',
        employees: '',
        founded_date: '1993-12-31',
        is_ios_certified: false,
        is_ts16949_certified: false,
        is_oe_supplier: false,
        attachments: [],
    },
    brand: {
        name: '',
        country: '',
        logo: {},
    },
    model: {
        brand_id: 0,
        region_id: undefined,
        serial: undefined,
        car_model_id: 0,
        trim: undefined,
        start_year: 1999,
        stop_year: 2005,
        body: undefined,
        engine_cc: undefined,
        engine_cyl: undefined,
        engine_type: undefined,
        engine_torque_nm: 0,
        engine_fuel_type: undefined,
        drive: undefined,
        transmission_type: undefined,
        seats: 0,
        doors: 0,
        weight_kg: 0,
        length_mm: 0,
        width_mm: 0,
        height_mm: 0,
        wheelbase_mm: 0,
        fuel_cap_l: 0,
    },
    carModel: {
        name: '',
        status: 0,
        brand_id: 0
    },
    product: {
        name: '',
        category_id: 0,
        images: [],
        profile: {},
        numbers: [],
        supplier_ids: [],
        model_ids: [],
    },
    inquiry: {
        brand_id: 0,
        images: [],
        model_id: 0,
        name: '',
        note: '',
        number: '',
        product_id: '',
        quantity: 0,
        state: '',
        unit: '',
        user_id: 0,
    },
});
